### ISSUE TITLE
Ошибка при вызове connection.search_read

### ISSUE THREAD

**Issue by nrot** [amironov73/PythonIrbis#15]
**Описание ошибки**
Использовалась версия библиотеки с GitHub, установленная вручную.
Вызов `connection.search_read` приводит к ошибке в `Field.parse`.

**Возпроизведение**
База данных RDR (Читателей): я так понимаю в рамках ИРБИС база вполне стандартная.
После подключения вызов 
```python
connection.search_read('"A=$"', 10)` 
```

Файл field.py метод parse: 
```python
 def parse(self, line: str) -> None:
        """
        Разбор текстового представления поля (в серверном формате).

        :param line: Строка с текстовым представлением.
        :return: None.
        """
        parts = line.split('#', 1) # line == '' - пустая строка
        self.tag = int(parts[0])  #Невозможно обратиться по индексу 0 так как длина равно 0
        if '^' not in parts[1]:
```

Увы набор данных предоставить здесь не могу так как они относятся к персональным данным, а их искажение может привести к невозможности воспроизведения ошибки. Остальные дополнительные сведения с радостью предоставлю.

**Comment by ri-gilfanov** [comment]
@nrot, исправил и у меня метод `connection.search_read()` сейчас работает нормально. Добавил дополнительную проверку на пустую строку в `AbstractRecord.parse(text)` (модуль `records/abstract.py`).

У меня пустая строка оказывалась последним элементом переменной `lines` в методе `search_read()` на строке 1775:
```
    lines = line.split("\x1F")
```
