### ISSUE TITLE
Пример программы не соответствует реальности

### ISSUE THREAD

**Issue by nrot** [amironov73/PythonIrbis#2]
**Describe the bug**
Пример [программы ](https://github.com/amironov73/PythonIrbis/blob/master/docs/chapter1.md#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC) не работает. В частности метод импорта модулей. 

**To Reproduce**
В примере описан метод подключения библиотеки как 

`import irbis`

При попытки обратиться к классу например Connection, ошибка

`AttributeError: module 'irbis' has no attribute 'Connection'`

Для исправления достаточно импортировать модуль core из irbis

```
import irbis.core
connection = irbis.core.Connection()
```

**Expected behavior**
Скорее всего неправильно сконфигурирован файл __init__.py в irbis

**Desktop (please complete the following information):**
- Windows 10 
- Python 3.7.4 
- PythonIrbis 0.0.71

**Comment by amironov73** [comment]
Fixed by 9cab9ab847d297ea2ebb4a29e38fdc18d4e6c6b2
