### ISSUE TITLE
не существует irbis.core 

### ISSUE THREAD

**Issue by chercgpb** [amironov73/PythonIrbis#23]
В примере не существует  irbis.core

```
import irbis.core as bars

client = bars.Connection()
client.connect('host', 6666, 'librarian', 'secret')
# Считываем формат краткого библиографического
# описания для базы IBIS
brief = client.read_text_file('2.IBIS.brief.pft')
print('BRIEF:', brief)
client.disconnect()
```

**Comment by nrot** [comment]
Добрый день. В библиотеке не существует модуля с именем ```irbis.core```. Вы нашли этот пример в официальной документации или где-то в примерах проекта?
Вы можете посмотреть пример подключения из официальной [документации](https://pythonirbis.readthedocs.io/ru/latest/chapter1.html#id4)

**Comment by amironov73** [comment]
Это был артефакт далеких времен, я его удалил, однако, на readthedocs почему-то документация не обновилась. Что можно сделать, чтобы readthedocs подхватил изменения?

**Comment by amironov73** [comment]
О! Сейчас посмотрел - отображается уже актуальная версия. Видимо, на readthedocs выкатывает обновленную документацию с задержкой. Можно закрывать.
